CREATE TABLE `onboarding_data` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`tenantId` int,
	`onboardingStatus` enum('in_progress','completed','reviewed') NOT NULL DEFAULT 'in_progress',
	`anrede` varchar(20),
	`titel` varchar(20),
	`vorname` varchar(100),
	`nachname` varchar(100),
	`telefon` varchar(50),
	`position` varchar(100),
	`firmenname` varchar(255),
	`rechtsform` varchar(50),
	`gruendungsjahr` varchar(10),
	`handelsregister` varchar(50),
	`umsatzsteuerID` varchar(50),
	`strasse` varchar(255),
	`plz` varchar(20),
	`ort` varchar(100),
	`land` varchar(50),
	`website` varchar(255),
	`portfolioGroesse` varchar(50),
	`anzahlObjekte` varchar(50),
	`objektarten` json,
	`standorte` text,
	`gesamtmietflaeche` varchar(50),
	`leerstandsquote` varchar(20),
	`durchschnittlicheMietrendite` varchar(20),
	`aktuelleFinanzierungen` varchar(50),
	`durchschnittlicherZinssatz` varchar(20),
	`restlaufzeiten` varchar(50),
	`tilgungsstruktur` varchar(50),
	`sicherheiten` text,
	`bankbeziehungen` text,
	`kapitalbedarf` varchar(50),
	`verwendungszweck` varchar(100),
	`zeithorizont` varchar(50),
	`gewuenschteStruktur` varchar(50),
	`investorentyp` varchar(50),
	`projektbeschreibung` text,
	`besondereAnforderungen` text,
	`agbAkzeptiert` boolean DEFAULT false,
	`datenschutzAkzeptiert` boolean DEFAULT false,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `onboarding_data_id` PRIMARY KEY(`id`)
);
